apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ajah.fullname" . }}-postgres
  labels:
    {{- include "ajah.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  serviceName: {{ include "ajah.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      {{- include "ajah.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        {{- include "ajah.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ajah.fullname" . }}-secret
                  key: postgres-password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.postgres.storage.storageClass }}
        storageClassName: {{ .Values.postgres.storage.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgres.storage.size }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ajah.fullname" . }}-postgres
  labels:
    {{- include "ajah.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  selector:
    {{- include "ajah.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
