apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ajah.fullname" . }}-redis
  labels:
    {{- include "ajah.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  serviceName: {{ include "ajah.fullname" . }}-redis
  replicas: 1
  selector:
    matchLabels:
      {{- include "ajah.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "ajah.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: {{ .Values.redis.port }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.redis.storage.storageClass }}
        storageClassName: {{ .Values.redis.storage.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.redis.storage.size }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ajah.fullname" . }}-redis
  labels:
    {{- include "ajah.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
  selector:
    {{- include "ajah.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
