apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ajah.fullname" . }}-secret
  labels:
    {{- include "ajah.labels" . | nindent 4 }}
type: Opaque
data:
  clickhouse-password: {{ .Values.clickhouse.password | b64enc | quote }}
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
